name: flyway
version: 9.12.0
summary: Version control for your database
description: |
    Version control for your database.
    Robust schema evolution across all your environments.
    With ease, pleasure and plain SQL. 
license: Apache-2.0

base: core18
confinement: strict
grade: stable

parts:
  flyway:
    plugin: dump
    source: https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$SNAPCRAFT_PROJECT_VERSION/flyway-commandline-$SNAPCRAFT_PROJECT_VERSION-linux-x64.tar.gz

apps:
  flyway:
    command: flyway
    plugs: [network, home, removable-media]
